Log message source details: sources=["/app/fdi/airflow/logs/dag_id=document_classifier/run_id=manual__2025-05-21T11:03:57.551309+00:00/task_id=classify_document/map_index=1/attempt=1.log"]
::group::Log message source details: sources=["/app/fdi/airflow/logs/dag_id=document_classifier/run_id=manual__2025-05-21T11:03:57.551309+00:00/task_id=classify_document/map_index=1/attempt=1.log"]
[2025-05-21, 16:33:57] INFO - DAG bundles loaded: dags-folder, example_dags: source="airflow.dag_processing.bundles.manager.DagBundlesManager"
[2025-05-21, 16:33:57] INFO - Filling up the DagBag from /app/fdi/dags/dynamic_input_agent.py: source="airflow.models.dagbag.DagBag"
[2025-05-21, 16:33:58] ERROR - Task failed with exception: source="task"
AssertionError: Expected code to be unreachable, but got: Assignment(agent='SharePoint Agent', path='https://hexawareonline.sharepoint.com/:b:/t/tensaiGPT-PRO...
File "/app/fdi/fdi_venv/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py", line 838 in run

File "/app/fdi/fdi_venv/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py", line 1130 in _execute_task

File "/app/fdi/fdi_venv/lib/python3.12/site-packages/airflow/sdk/bases/operator.py", line 408 in wrapper

File "/app/fdi/fdi_venv/lib/python3.12/site-packages/airflow_ai_sdk/operators/agent.py", line 44 in execute

File "/app/fdi/fdi_venv/lib/python3.12/site-packages/airflow/sdk/bases/operator.py", line 408 in wrapper

File "/app/fdi/fdi_venv/lib/python3.12/site-packages/airflow/sdk/bases/decorator.py", line 251 in execute

File "/app/fdi/fdi_venv/lib/python3.12/site-packages/airflow/sdk/bases/operator.py", line 408 in wrapper

File "/app/fdi/fdi_venv/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py", line 216 in execute

File "/app/fdi/fdi_venv/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py", line 239 in execute_callable

File "/app/fdi/fdi_venv/lib/python3.12/site-packages/airflow/sdk/execution_time/callback_runner.py", line 81 in run

File "/app/fdi/dags/dynamic_input_agent.py", line 383 in classify_document

File "/app/fdi/fdi_venv/lib/python3.12/site-packages/pydantic_ai/agent.py", line 578 in run_sync

File "/usr/lib/python3.12/asyncio/base_events.py", line 687 in run_until_complete

File "/app/fdi/fdi_venv/lib/python3.12/site-packages/pydantic_ai/agent.py", line 329 in run

File "/app/fdi/fdi_venv/lib/python3.12/site-packages/pydantic_ai/agent.py", line 1454 in __anext__

File "/app/fdi/fdi_venv/lib/python3.12/site-packages/pydantic_graph/graph.py", line 790 in __anext__

File "/app/fdi/fdi_venv/lib/python3.12/site-packages/pydantic_graph/graph.py", line 763 in next

File "/app/fdi/fdi_venv/lib/python3.12/site-packages/pydantic_ai/_agent_graph.py", line 264 in run

File "/app/fdi/fdi_venv/lib/python3.12/site-packages/pydantic_ai/_agent_graph.py", line 317 in _make_request

File "/app/fdi/fdi_venv/lib/python3.12/site-packages/pydantic_ai/models/openai.py", line 193 in request

File "/app/fdi/fdi_venv/lib/python3.12/site-packages/pydantic_ai/models/openai.py", line 262 in _completions_create

File "/app/fdi/fdi_venv/lib/python3.12/site-packages/pydantic_ai/models/openai.py", line 327 in _map_message

File "/app/fdi/fdi_venv/lib/python3.12/site-packages/pydantic_ai/models/openai.py", line 382 in _map_user_message

File "/app/fdi/fdi_venv/lib/python3.12/site-packages/pydantic_ai/models/openai.py", line 452 in _map_user_prompt

File "/usr/lib/python3.12/typing.py", line 2409 in assert_never

[2025-05-21, 16:33:58] INFO - Task instance is in running state: chan="stdout": source="task"
[2025-05-21, 16:33:58] INFO -  Previous state of the Task instance: TaskInstanceState.QUEUED: chan="stdout": source="task"
[2025-05-21, 16:33:58] INFO - Current task name:classify_document: chan="stdout": source="task"
[2025-05-21, 16:33:58] INFO - Dag name:document_classifier: chan="stdout": source="task"
[2025-05-21, 16:33:58] INFO - Executing LLM call: chan="stdout": source="task"
[2025-05-21, 16:33:58] INFO - Task instance in failure state: chan="stdout": source="task"
[2025-05-21, 16:33:58] INFO - Task start: chan="stdout": source="task"
[2025-05-21, 16:33:58] INFO - Task:<Task(AgentDecoratedOperator): classify_document>: chan="stdout": source="task"
[2025-05-21, 16:33:58] INFO - Failure caused by Expected code to be unreachable, but got: Assignment(agent='SharePoint Agent', path='https://hexawareonline.sharepoint.com/:b:/t/tensaiGPT-PRO...: chan="stdout": source="task"
