Log message source details: sources=["/app/fdi/airflow/logs/dag_id=image_processor/run_id=manual__2025-05-26T05:33:30.026002+00:00/task_id=process_image_get_json/attempt=1.log"]
[2025-05-26, 11:03:39] INFO - DAG bundles loaded: dags-folder, example_dags: source="airflow.dag_processing.bundles.manager.DagBundlesManager"
[2025-05-26, 11:03:39] INFO - Filling up the DagBag from /app/fdi/dags/image_processing_agent.py: source="airflow.models.dagbag.DagBag"
[2025-05-26, 11:03:44] WARNING - Neither CUDA nor MPS are available - defaulting to CPU. Note: This module is much faster with a GPU.: source="easyocr.easyocr"
[2025-05-26, 11:03:47] INFO - {{ task_instance.xcom_pull(task_ids='format_final_output', dag_id='image_processor', key='return_value') }}: chan="stdout": source="task"
[2025-05-26, 11:03:47] INFO - Done. Returned value was: <coroutine object Agent.run at 0x75cb1742fdf0>: source="airflow.task.operators.airflow_ai_sdk.operators.agent.AgentDecoratedOperator"
[2025-05-26, 11:03:47] ERROR - Task failed with exception: source="task"
TypeError: 'coroutine' object is not iterable
File "/app/fdi/fdi_venv/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py", line 838 in run

File "/app/fdi/fdi_venv/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py", line 1130 in _execute_task

File "/app/fdi/fdi_venv/lib/python3.12/site-packages/airflow/sdk/bases/operator.py", line 408 in wrapper

File "/app/fdi/fdi_venv/lib/python3.12/site-packages/airflow_ai_sdk/operators/agent.py", line 52 in execute

File "/app/fdi/fdi_venv/lib/python3.12/site-packages/airflow_ai_sdk/operators/agent.py", line 48 in execute

File "/app/fdi/fdi_venv/lib/python3.12/site-packages/pydantic_ai/agent.py", line 578 in run_sync

File "/usr/lib/python3.12/asyncio/base_events.py", line 687 in run_until_complete

File "/app/fdi/fdi_venv/lib/python3.12/site-packages/pydantic_ai/agent.py", line 329 in run

File "/app/fdi/fdi_venv/lib/python3.12/site-packages/pydantic_ai/agent.py", line 1454 in __anext__

File "/app/fdi/fdi_venv/lib/python3.12/site-packages/pydantic_graph/graph.py", line 790 in __anext__

File "/app/fdi/fdi_venv/lib/python3.12/site-packages/pydantic_graph/graph.py", line 763 in next

File "/app/fdi/fdi_venv/lib/python3.12/site-packages/pydantic_ai/_agent_graph.py", line 264 in run

File "/app/fdi/fdi_venv/lib/python3.12/site-packages/pydantic_ai/_agent_graph.py", line 317 in _make_request

File "/app/fdi/fdi_venv/lib/python3.12/site-packages/pydantic_ai/models/openai.py", line 193 in request

File "/app/fdi/fdi_venv/lib/python3.12/site-packages/pydantic_ai/models/openai.py", line 262 in _completions_create

File "/app/fdi/fdi_venv/lib/python3.12/site-packages/pydantic_ai/models/openai.py", line 327 in _map_message

File "/app/fdi/fdi_venv/lib/python3.12/site-packages/pydantic_ai/models/openai.py", line 382 in _map_user_message

File "/app/fdi/fdi_venv/lib/python3.12/site-packages/pydantic_ai/models/openai.py", line 408 in _map_user_prompt

[2025-05-26, 11:03:47] INFO - Task instance is in running state: chan="stdout": source="task"
[2025-05-26, 11:03:47] INFO -  Previous state of the Task instance: TaskInstanceState.QUEUED: chan="stdout": source="task"
[2025-05-26, 11:03:47] INFO - Current task name:process_image_get_json: chan="stdout": source="task"
[2025-05-26, 11:03:47] INFO - Dag name:image_processor: chan="stdout": source="task"
[2025-05-26, 11:03:47] INFO - Executing LLM call: chan="stdout": source="task"
[2025-05-26, 11:03:47] INFO - Prompt: <coroutine object Agent.run at 0x75cb1742fdf0>: chan="stdout": source="task"
[2025-05-26, 11:03:47] INFO - Error: 'coroutine' object is not iterable: chan="stdout": source="task"
[2025-05-26, 11:03:47] INFO - Task instance in failure state: chan="stdout": source="task"
[2025-05-26, 11:03:47] INFO - Task start: chan="stdout": source="task"
[2025-05-26, 11:03:47] INFO - Task:<Task(AgentDecoratedOperator): process_image_get_json>: chan="stdout": source="task"
[2025-05-26, 11:03:47] INFO - Failure caused by 'coroutine' object is not iterable: chan="stdout": source="task"
