Log message source details: sources=["/app/fdi/airflow/logs/dag_id=document_classifier_dag/run_id=manual__2025-05-22T06:41:36.628487+00:00/task_id=classify/map_index=0/attempt=1.log"]
::group::Log message source details: sources=["/app/fdi/airflow/logs/dag_id=document_classifier_dag/run_id=manual__2025-05-22T06:41:36.628487+00:00/task_id=classify/map_index=0/attempt=1.log"]
[2025-05-22, 12:11:37] INFO - DAG bundles loaded: dags-folder, example_dags: source="airflow.dag_processing.bundles.manager.DagBundlesManager"
[2025-05-22, 12:11:37] INFO - Filling up the DagBag from /app/fdi/dags/dynamic_input_agent.py: source="airflow.models.dagbag.DagBag"
[2025-05-22, 12:11:38] INFO - Running classifier for: /app/fdi/Documents/FRD.pptx: source="airflow.utils.log.logging_mixin.LoggingMixin"
[2025-05-22, 12:11:38] INFO - Task instance is in running state: chan="stdout": source="task"
[2025-05-22, 12:11:38] INFO -  Previous state of the Task instance: TaskInstanceState.QUEUED: chan="stdout": source="task"
[2025-05-22, 12:11:38] INFO - Current task name:classify: chan="stdout": source="task"
[2025-05-22, 12:11:38] INFO - Dag name:document_classifier_dag: chan="stdout": source="task"
[2025-05-22, 12:11:39] ERROR - Task failed with exception: source="task"
AttributeError: 'AgentRunResult' object has no attribute 'output'
File "/app/fdi/fdi_venv/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py", line 838 in run

File "/app/fdi/fdi_venv/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py", line 1130 in _execute_task

File "/app/fdi/fdi_venv/lib/python3.12/site-packages/airflow/sdk/bases/operator.py", line 408 in wrapper

File "/app/fdi/fdi_venv/lib/python3.12/site-packages/airflow/sdk/bases/decorator.py", line 251 in execute

File "/app/fdi/fdi_venv/lib/python3.12/site-packages/airflow/sdk/bases/operator.py", line 408 in wrapper

File "/app/fdi/fdi_venv/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py", line 216 in execute

File "/app/fdi/fdi_venv/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py", line 239 in execute_callable

File "/app/fdi/fdi_venv/lib/python3.12/site-packages/airflow/sdk/execution_time/callback_runner.py", line 81 in run

File "/app/fdi/dags/dynamic_input_agent.py", line 87 in classify

[2025-05-22, 12:11:39] INFO - Task instance in failure state: chan="stdout": source="task"
[2025-05-22, 12:11:39] INFO - Task start: chan="stdout": source="task"
[2025-05-22, 12:11:39] INFO - Task:<Task(_PythonDecoratedOperator): classify>: chan="stdout": source="task"
[2025-05-22, 12:11:39] INFO - Failure caused by 'AgentRunResult' object has no attribute 'output': chan="stdout": source="task"
