Log message source details: sources=["/app/fdi/airflow/logs/dag_id=document_classifier_dag/run_id=manual__2025-05-21T18:34:15.909560+00:00/task_id=classify/map_index=1/attempt=1.log"]
[2025-05-22, 00:04:16] INFO - DAG bundles loaded: dags-folder, example_dags: source="airflow.dag_processing.bundles.manager.DagBundlesManager"
[2025-05-22, 00:04:16] INFO - Filling up the DagBag from /app/fdi/dags/dyno3.py: source="airflow.models.dagbag.DagBag"
[2025-05-22, 00:04:17] INFO - Running classifier for: https://hexawareonline.sharepoint.com/:b:/t/tensaiGPT-PROD-HR-Docs/ET0W0clrClhBrA7ZLzCoOmEBHq0vg-rFuGuEwb40Weq8zQ?e=6BkU3C: source="airflow.utils.log.logging_mixin.LoggingMixin"
[2025-05-22, 00:04:17] INFO - Task instance is in running state: chan="stdout": source="task"
[2025-05-22, 00:04:17] INFO -  Previous state of the Task instance: TaskInstanceState.QUEUED: chan="stdout": source="task"
[2025-05-22, 00:04:17] INFO - Current task name:classify: chan="stdout": source="task"
[2025-05-22, 00:04:17] INFO - Dag name:document_classifier_dag: chan="stdout": source="task"
[2025-05-22, 00:04:17] INFO - Executing LLM call: chan="stdout": source="task"
Calling tool detect_images_in_document with args {"path":"https://hexawareonline.sharepoint.com/:b:/t/tensaiGPT-PROD-HR-Docs/ET0W0clrClhBrA7ZLzCoOmEBHq0vg-rFuGuEwb40Weq8zQ?e=6BkU3C"}: chan="stdout": source="task"
[2025-05-22, 00:04:22] ERROR - Task failed with exception: source="task"
JSONDecodeError: Expecting value: line 1 column 1 (char 0)
File "/app/fdi/fdi_venv/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py", line 838 in run

File "/app/fdi/fdi_venv/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py", line 1130 in _execute_task

File "/app/fdi/fdi_venv/lib/python3.12/site-packages/airflow/sdk/bases/operator.py", line 408 in wrapper

File "/app/fdi/fdi_venv/lib/python3.12/site-packages/airflow_ai_sdk/operators/agent.py", line 44 in execute

File "/app/fdi/fdi_venv/lib/python3.12/site-packages/airflow/sdk/bases/operator.py", line 408 in wrapper

File "/app/fdi/fdi_venv/lib/python3.12/site-packages/airflow/sdk/bases/decorator.py", line 251 in execute

File "/app/fdi/fdi_venv/lib/python3.12/site-packages/airflow/sdk/bases/operator.py", line 408 in wrapper

File "/app/fdi/fdi_venv/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py", line 216 in execute

File "/app/fdi/fdi_venv/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py", line 239 in execute_callable

File "/app/fdi/fdi_venv/lib/python3.12/site-packages/airflow/sdk/execution_time/callback_runner.py", line 81 in run

File "/app/fdi/dags/dyno3.py", line 80 in classify

File "/usr/lib/python3.12/json/__init__.py", line 346 in loads

File "/usr/lib/python3.12/json/decoder.py", line 337 in decode

File "/usr/lib/python3.12/json/decoder.py", line 355 in raw_decode

[2025-05-22, 00:04:22] INFO - Task instance in failure state: chan="stdout": source="task"
[2025-05-22, 00:04:22] INFO - Task start: chan="stdout": source="task"
[2025-05-22, 00:04:22] INFO - Task:<Task(AgentDecoratedOperator): classify>: chan="stdout": source="task"
[2025-05-22, 00:04:22] INFO - Failure caused by Expecting value: line 1 column 1 (char 0): chan="stdout": source="task"
